### ISSUE TITLE
ACCOUNT - enable manual writing of birth date

### ISSUE THREAD

**Issue by AnaBlidaru** [code4romania/teo#212]
The only available option to introduce a date is by going back from today, month my month. It takes a long time, and the arrows move for each month, as the height of the pop-up differs according to the number of weeks. Most likely, no one will be able to add the true date of birth.
![IMG_D9930E5BF51A-1](https://github.com/code4romania/teo/assets/143508353/1db83961-339a-4580-bec3-a330525da6d5)

Users need to be able to insert their birth date manually.
The same observation for adding the issuing date and expiration date for the identity card.

**Comment by anastk-code4** [comment]
Tested. 
User can select year > month > day. For now it s good enough
