### ISSUE TITLE
Both email and phone number required despite 'Email OR phone number' option

### ISSUE THREAD

**Issue by cristinamhm** [code4romania/teo#214]
### Description

When attempting to create an account, I noticed that the registration form requires both an email address and a phone number to be filled in, even though there's an option at the top that suggests I can use either my email or phone number. This seems contradictory and confusing

### Preconditions

You have reached the registration page .
You have chosen the option "Email or phone number" for creating your account.

### Test Data

-

### Steps of Reproduction

Reach the registration page.
Press on the "Email or phone number" option at the top.
Begin filling out the registration form.
Notice that both the email and phone number fields are marked as mandatory (required).

**Comment by anastk-code4** [comment]
Labeled this as microcopy - will fix it from labelling
