### ISSUE TITLE
Event target cannot be changed

### ISSUE THREAD

**Issue by danut3101** [code4romania/teo#221]
### Description

During the editing an existing event , the target cannot be changed ad appear as disabled

### Preconditions

On editing event

### Test Data

.

### Steps of Reproduction

1. From left menu select Events
2. from events tab, events list go to the right side on the contextual menu and select "edit event"
3. in target section try to select other radio option than selected one.

### Expected Result

To be able to select other option, as result of a initial miss-click or  a revision of event.

### Actual Result
The radio group is disabled and no option can be selected

### Notes (optional)
.

**Comment by birloiflorian** [comment]
Works as expected
