### ISSUE TITLE
[Join NGO] A volunteer can rejoin an NGO they were previously member of, without access request or access code

### ISSUE THREAD

**Issue by BirtasAdrian** [code4romania/teo#227]
### Description

The volunteer can rejoin in organisation without being asked for an invitation or an access code.

### Preconditions

1.To have the mobile app installed and logged in as volunteer.
2. To have been in an organization

### Steps of Reproduction
1. Go to "Voluntar" section 
2.  Tap on "Profil Organizatie" button
3. Tap on "Părăseşte Organizaţia" button
4. Tap again on "Părăseşte Organizaţia" button
5. Tap again on "Părăseşte Organizaţia" button
6. Tap "Reintra in organizatie" button

### Expected Result

The volunteer should need a invitation or access code to rejoin the organization. 

### Actual Result

The volunteer does not need an invitation or access code to rejoin the organization. 

https://github.com/code4romania/teo/assets/90641668/b4dfcac0-20a9-49dc-98e6-91bb0e04eeb8

**Comment by birloiflorian** [comment]
Works as intended.
